# Generated by Django 5.0.1 on 2024-02-09 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_type', models.CharField(choices=[('appetizer', 'Appetizer'), ('mainCourse', 'Main Course'), ('dessert', 'Dessert')], max_length=20)),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_price', models.IntegerField()),
                ('dish_description', models.TextField()),
                ('dish_image', models.ImageField(blank=True, null=True, upload_to='static/dish_image')),
            ],
            options={
                'ordering': ['dish_type'],
            },
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('family_members', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DishIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.JSONField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineRestaurant.dish')),
            ],
            options={
                'ordering': ['dish__dish_type'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineRestaurant.user_info')),
            ],
        ),
    ]
