# Generated by Django 5.0.1 on 2024-02-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineRestaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='table_id',
            new_name='customer_id',
        ),
    ]
