# Generated by Django 5.0.1 on 2024-02-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineRestaurant', '0002_rename_customer_order_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='customer_id',
            new_name='table_id',
        ),
    ]
