# Generated by Django 5.0.1 on 2024-03-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineRestaurant', '0005_alter_order_customer_id_alter_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
    ]
