# Generated by Django 5.0.1 on 2024-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineRestaurant', '0006_remove_order_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.TextField(),
        ),
    ]
