# Generated by Django 5.0.1 on 2024-03-15 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineRestaurant', '0007_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='OnlineRestaurant.user_info'),
        ),
    ]
