# Generated by Django 5.0.1 on 2024-03-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineRestaurant', '0008_order_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_order_completed',
            field=models.BooleanField(default=False),
        ),
    ]
